from setuptools import setup, find_packages
import sys, os

version = '0.9.9'

setup(name="holland",
      version=version,
      description="Holland Core Plugins",
      long_description="""\
      These are the plugins required for basic Holland functionality.
      """,
      classifiers=[], # Get strings from http://pypi.python.org/pypi?%3Aaction=list_classifiers
      keywords="",
      author="Rackspace",
      author_email="holland-devel@googlegroups.com",
      url='http://www.hollandbackup.org/',
      license="3-Clause BSD",
      packages=find_packages(exclude=["ez_setup", "examples", "tests"]),
      include_package_data=True,
      zip_safe=True,
      test_suite='tests',
      install_requires=[
        # 'configobj' # currently this is bundled internally
      ],
      entry_points="""
      # Scripts generated by setuptools
      [console_scripts]
      holland = holland.cli:main

      # Holland subcommands
      [holland.commands]
      help = holland.cli.commands.builtin.help:Help
      listplugins = holland.cli.command.builtin.list_plugins:ListPlugins
      listbackups = holland.cli.command.builtin.list_backups:ListBackups
      backup = holland.cli.command.builtin.backup:Backup
      mk-config = holland.cli.command.builtin.mk_config:MkConfig
      purge = holland.cli.command.builtin.purge:Purge
      #restore = holland.cli.command.builtin.restore:Restore
      """,
      namespace_packages=['holland', 'holland.backup', 'holland.lib', 'holland.commands'],
      )
