from setuptools import setup, find_packages
import sys, os
from holland.version import __version__

extra = {}
if sys.version_info >= (3, 0):
    extra.update(
        use_2to3=True,
        use_2to3_fixers=[]
    )

setup(
    name="holland",
    version=__version__,
    description="Holland Core Framework",
    long_description="""\
    This package provides the core functionality for
    performing backups along with a command line client interface.
    """,
    author="Rackspace",
    author_email="holland-discuss@lists.launchpad.net",
    url='http://www.hollandbackup.org',
    license="3-Clause BSD",
    packages=find_packages(exclude=["ez_setup", "examples", "tests", "tests.*"]),
    include_package_data=True,
    zip_safe=False,
    test_suite='tests',
    install_requires=[
    ],
    entry_points="""
    # Scripts generated by setuptools
    [console_scripts]
    holland = holland.cli.main:holland
    """,
    namespace_packages=[],
    **extra
)
